name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore  ./src/libfintx.sln
    - name: Build
      run: dotnet build --no-restore ./src/libfintx.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/libfintx.sln
